.travis.yml, README.md, configs/example, configs/example-configmap.yaml
Update and fix the instructions.
=> Update README and add example config

artifacts/scripts/publish_client_go.sh, artifacts/scripts/publish_sample_apiserver.sh, artifacts/scripts/publish_sample_controller.sh
The godep tests from my manual test script.
TODO:
=> Add smoke tests for sample-{apiserver,controller}

Makefile, README.md, artifacts/manifests/podspec.yaml, artifacts/manifests/service.yaml, cmd/publishing-bot/healthz.go, cmd/publishing-bot/main.go, cmd/publishing-bot/publisher.go
=> Add healthz server

cmd/publishing-bot/publisher.go
=> Re-enable kube 1.7

artifacts/scripts/util.sh, cmd/publishing-bot/config/rules.go, cmd/publishing-bot/publisher.go
=> Add skipGodeps flag to repo rules

artifacts/scripts/publish_template.sh, cmd/sync-tags/godeps.go, cmd/sync-tags/godeps_test.go, cmd/sync-tags/main.go
Fixes https://github.com/kubernetes/publishing-bot/issues/12
=> Update Godeps.json during tagging to point to tags

artifacts/scripts/construct.sh, artifacts/scripts/util.sh, cmd/publishing-bot/config/rules.go, cmd/publishing-bot/publisher.go, configs/kubernetes-rules-configmap.yaml
Fixes https://github.com/kubernetes/sample-controller/issues/6.
=> Add required-packages field to include code-generator

cmd/init-repo/main.go, cmd/publishing-bot/config/rules.go, cmd/publishing-bot/main.go, cmd/publishing-bot/publisher.go
Detects the URL in `-rule-file` value and fetch the rules from remote URL.
=> allow to fetch rules from URL

cmd/sync-tags/main.go
The date was 1/1/1970. Git push failed.
=> Fix time of extra tag commit

configs/kubernetes-rules-configmap.yaml
=> Add 1.10 branches

artifacts/scripts/util.sh
Fixes issues due to https://github.com/kubernetes/kubernetes/pull/59587#issuecomment-368575420.
=> Cope with extra files in Godeps/ directory

artifacts/scripts/util.sh
While this makes the code easier to read, I also have the suspicioun that the `if ! cmd1 | cmd2 || cmd3; then`
syntax did not work properly inside the script, while it work in an interactive shell. Maybe
a shell bug.
=> Simplify is-merge check

artifacts/scripts/construct.sh, artifacts/scripts/util.sh, cmd/publishing-bot/config/rules.go, cmd/publishing-bot/publisher.go, cmd/publishing-bot/publisher_logger.go, configs/example-rules-configmap.yaml, configs/kubernetes-rules-configmap.yaml
Fixes https://github.com/kubernetes/publishing-bot/issues/49
Fixes https://github.com/kubernetes/client-go/issues/189
=> Implement RecursiveDeletePatterns and delete BUILD files in kube rules

cmd/init-repo/main.go
ref: https://github.com/kubernetes/kubernetes/pull/62037
=> Bump godep version to v80

README.md
=>  Grammatical errors

artifacts/scripts/util.sh
This stops the commit loop visible in https://github.com/kubernetes/apiextensions-apiserver/commits/master.
We had a number of steps, each avoiding commits if nothing changed, but without a check for all of them in a row (leading to the loop):
- remove bazel BUILD files
- run godep save/restore
- add expicitly required packages (like k8s.io/code-generator).
Each of these alone creates a diff, but all 3 squashed are empty.
=> Squash godep commits or skip all of them if nothing changed

artifacts/scripts/util.sh
=> Typo fix: paramter->parameter

configs/kubernetes-rules-configmap.yaml
=> Add 1.11 branches

configs/kubernetes-rules-configmap.yaml
In preparation of https://github.com/kubernetes/kubernetes/pull/64731.
=> Remove Gopkg.toml file

README.md
We have https://github.com/kubernetes/kubernetes/issues/56876 now. \o/
/assign sttts
=> README: remove reporting issues from Known Issues

Dockerfile, configs/example-configmap.yaml, configs/example-rules-configmap.yaml, configs/kubernetes-configmap.yaml, configs/kubernetes-rules-configmap.yaml
The latter was broken.
Fixes https://github.com/kubernetes/publishing-bot/issues/75
=> Switch to debian:jessie image away from google/debian

cmd/publishing-bot/publisher_logger_test.go
=> Fixes missing license 

artifacts/scripts/util.sh
Fixes https://github.com/kubernetes/publishing-bot/issues/95.
We solve this by looking for the first (time-wise) fast-forward merge which introduced the subdirectory. The second-parent (on master) is the branching point for the new branch.
We do not support (yet) a publishing subdirectory that was actually created on a releaes branch.
=> Handle branching points for new branches which do not contain subdir

artifacts/scripts/construct.sh, cmd/publishing-bot/publisher.go, cmd/sync-tags/main.go, configs/kubernetes-rules-configmap.yaml, hack/fetch-all-latest-and-push.sh
- skip cherry-picking if published hash matches last upstream hash
- skip commit mapping computation if no new tag is found
=> Speed up if nothing changed on a branch

configs/kubernetes-rules-configmap.yaml, hack/fetch-all-latest-and-push.sh
Based on https://github.com/kubernetes/publishing-bot/pull/97
=> Add 1.12 branches to new staging repos

artifacts/scripts/construct.sh, artifacts/scripts/util.sh, cmd/publishing-bot/publisher.go
We did not checkout master before reading the rules file, potentially from the source repo.
Also the source repo branch logic gave dirty output.
=> Clean up updateSourceRepo and checkout branch before rule loading

cmd/sync-tags/main.go
Delete tags not on source branch early. Don't compute source-target map if no new tag is found.
=> Speed-up no-op tagging

artifacts/scripts/construct.sh, cmd/publishing-bot/publisher.go, cmd/sync-tags/main.go
- fix sync-tags npe
- fix source fetch of tags (go-git fetch default is not fetch them)
- prune upstream and origin fetch in sync repo to allow branch regeneration
=> Misc fixes

pkg/git/mainline.go
A commit might be ancestor of multiple merges into the mainline. Only the first of those merges is considered the merge point of that commit. To find it we have to traverse mainline merges from oldest to newest, storing the first appearance of a commit as ancestor of a merge.
All credit goes to @nikhita for uncovering this.
=> Fix merge point calculation for repeated merges with same branch commit

configs/kubernetes-rules-configmap.yaml, hack/fetch-all-latest-and-push.sh
added bootstrap repo per https://github.com/kubernetes/kubernetes/pull/67356#issuecomment-414250981
=> added bootstrap repo.

configs/kubernetes-rules-configmap.yaml, hack/fetch-all-latest-and-push.sh
- Repo creation request: https://github.com/kubernetes/org/issues/147
- Repo with initial empty commit: https://github.com/kubernetes/cloud-provider
- PR against test-infra for branch protection: https://github.com/kubernetes/test-infra/pull/9739
- Dependencies: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/Godeps/Godeps.json
/cc @dims @sttts 
/assign @sttts
=> Add cloud-provider repo

.travis.yml, README.md
Ref: https://github.com/kubernetes/test-infra/pull/9895
Made sure that introducing a compilation error fails and that master is green in https://github.com/kubernetes/publishing-bot/pull/127.
/assign @sttts
=> Remove travis in favor of Prow

OWNERS
We have been working/reviewing on publishing-bot for a while.
/cc @mfojtik @sttts 
/assign @sttts
=> Add mfojtik and nikhita as reviewers

cmd/collapsed-kube-commit-mapper/main.go
Fix typo: corresonding -> corresponding
=> Fix typo: corresonding -> corresponding

Makefile, README.md, artifacts/manifests/rs.yaml
ReplicationControllers have been replaced by RSs long ago.
=> Switch to ReplicaSet

Dockerfile, artifacts/scripts/construct.sh, artifacts/scripts/util.sh, cmd/collapsed-kube-commit-mapper/main.go, cmd/init-repo/main.go, configs/kubernetes-rules-configmap.yaml, hack/fetch-all-latest-and-push.sh, pkg/git/mainline.go, pkg/git/mapping.go
Fixed a number of things (see commits), including bumping the base image to debian stretch (because some mercurial based dependencies couldn't be downloaded anymore due to old SSL errors) and new git. Went through fine in my sttts org.
=> Fix publishing of component-base

Makefile, configs/kubernetes-rules-configmap.yaml
Forgot to commit some changes.
=> Fix deployment with rules from the repo

artifacts/scripts/util.sh
This commit adds an exception list for commits containing bad godep changes
(eg client-go depending on apiserver) and skips godeps generation for these
commits.
Note that we will still reset godeps for each commit (including the bad commit).
And the correct godep generation will take place once it encounters a good commit.
This is a temporary fix and should probably be reverted because it is not always
true that there will be a commit having the correct godep changes after a bad one
_immediately_. If there isn't a good commit after a bad one immediately, the commits
between them will have bad Godeps.json.
---
This is the bad commit that needs to skip godeps generation - https://github.com/kubernetes/kubernetes/commit/e2a017327c1af628f4f0069cbd49865ad1e81975 and this is the good commit …
=> Skip godeps generation for commits containing incorrect godep changes

Makefile, cmd/init-repo/main.go, cmd/publishing-bot/install_golang.go, cmd/publishing-bot/publisher.go
Necessary if the rules file comes from a repo.
=> Move golang download to construction time

cmd/publishing-bot/config/rules.go, cmd/validate-rules/main.go
Change-Id: I3e9c8eb2542b50f81ba7cc1ea594f2a12384f9dd
=> Make validate-rules command a bit more verbose

artifacts/scripts/construct.sh, cmd/init-repo/main.go, cmd/publishing-bot/publisher.go, cmd/sync-tags/main.go, configs/kubernetes-nightly, configs/kubernetes-nightly-configmap.yaml, configs/kubernetes-nightly-rules-configmap.yaml, pkg/golang/install.go
- fix apiversion
- add missing file
- fix source-org
- run git config with user.email and user.name
- install default golang in init-repo itself
Change-Id: I102b0ae11aa141bc338fcfcea9b9913c600cc745
=> Fixes for running kubernetes-nightly config in CNCF cluster

OWNERS
This PR updates OWNERS to current reviewers.
/assign @dims @sttts 
@apelisse @marun @munnerz Let me know if you'd like to stay and I can add you back. :)
I'll keep this open till EOW so that everyone can chime in.
=> Update OWNERS to current reviewers

cmd/publishing-bot/main.go
Lets not wait 4 hours and retry quickly. If this works, we can add another parameter instead of hardcoding 5 mins.
Change-Id: I2ab92772f417124c4684bb5fb17bc5437923812d
=> Retry quickly when references changed

cmd/publishing-bot/main.go, cmd/publishing-bot/publisher.go
Ref: https://github.com/kubernetes/publishing-bot/pull/133#discussion_r232567955
/cc @dims @mfojtik @sttts
=> Don't set healthz on dry run

cmd/publishing-bot/main.go
Ref: https://kubernetes.slack.com/archives/C2C40FMNF/p1554206338033300?thread_ts=1554125684.027900&cid=C2C40FMNF
=> Fix waitFor calculation

Gopkg.lock, Gopkg.toml, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/dotgit/dotgit.go, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/dotgit/dotgit_setref.go, vendor/gopkg.in/src-d/go-git.v4/storage/memory/storage.go
Ref: https://github.com/nikhita/go-git/pull/1
For https://github.com/kubernetes/publishing-bot/issues/162
/assign @dims @sttts
=> Bump to private branch to display more info in error messages

artifacts/scripts/construct.sh
It's not set if skipGodeps is false in the rules file.
=> Cope with undefined PUBLISHER_BOT_GENERATE_GODEPS

configs/kubernetes-godeps
Ref: https://github.com/kubernetes/k8s.io/pull/282
Like https://github.com/kubernetes/publishing-bot/pull/198, but for the godeps branch
/assign @sttts @dims
=> Use gcr.io/k8s-staging-publishing-bot for storing godeps image

artifacts/scripts/util.sh, cmd/sync-tags/gomod.go
From Go 1.13, the go command defaults to downloading modules from the
public Go module mirror at proxy.golang.org. It also defaults to
validating downloaded modules, regardless of source, against the public
Go checksum database at sum.golang.org.
To avoid this validation for all non-published SHAs of staging repos,
we set the GOPRIVATE env var.
Ref: https://golang.org/cmd/go/#hdr-Module_configuration_for_non_public_modules
Without this, we get errors like:
```
+ GO111MODULE=on
+ GOPROXY=https://proxy.golang.org
+ go mod download
verifying k8s.io/api@v0.0.0-20191112131459-ab1b4ad002da/go.mod: k8s.io/api@v0.0.0-20191112131459-ab1b4ad002da/go.mod: reading https://sum.golang.org/lookup/k8s.io/api@v0.0.0-20191112131459-ab1b4ad002da: 410 Gone
verifying …
```
=> Set GOPRIVATE to avoid validating unpublished SHAs

OWNERS
Can i please help push things along!
=> propose dims as approver

Makefile, artifacts/manifests/podspec.yaml, configs/kubernetes
Signed-off-by: Arnaud Meukam <ameukam@gmail.com>
=> Prepare publishing-bot migration

cmd/sync-tags/gomod.go
Consider a repo (like component-base) that depends on apimachinery, api
(which depnds on apimachinery) and client-go (which depends on
apimachinery and api). In the current case, sync-tags updates the tags
in component-base's go.mod in the following way:
1. Update tag for apimachinery, run `go mod tidy`
2. Update tag for api, run `go mod tidy`
3. Update tag for client-go, run `go mod tidy`
If we remove a package from api and it's references in client-go in k/k,
step 2 fails while running `go mod tidy` because the go.mod file still
contains the old client-go version i.e. client-go still references
the removed package.
To fix this, we should update tags for all dependencies and _then_ run
`go mod tidy`. We also use this approach in util.sh while syncing branches
using pseudoversions so we …
=> sync-tags: run go mod tidy after updating deps in go.mod

cmd/sync-tags/main.go
If git is used directly while fetching tags, go-git doesn't recognize
annotated tags consistently. For example, there are instances where
it considers `refs/tags/upstream/*` as lightweight tags even though
`git for-each-ref refs/tags` clearly shows them as annotated tags.
This commits updates the fetch operation to use go-git directly to avoid
any inconsistencies while fetching and storing tags. Using go-git
removes this inconsistency and all annotated tags are recognized
properly.
Also, go-git now supports `*` in refspecs - https://github.com/src-d/go-git/blob/v4.9.1/config/refspec.go#L11.
---
We came across this error while deploying the bot recently. The bot doesn't recognize `refs/tags/upstream/*` as annotated, which makes sync-tags think that there are no new upstream tags and it …
=> sync-tags: use go-git for fetching tags

configs/example-rules-configmap.yaml
Name should belong to an array:
```
type BranchRule struct {
Name string `yaml:"name"`
// a valid go version string like 1.10.2 or 1.10
GoVersion string `yaml:"go"`
// k8s.io/* repos the branch rule depends on
Dependencies     []Dependency `yaml:"dependencies,omitempty"`
Source           Source       `yaml:"source"`
RequiredPackages []string     `yaml:"required-packages,omitempty"`
}
// a collection of publishing rules for a single destination repo
type RepositoryRule struct {
DestinationRepository string       `yaml:"destination"`
Branches              []BranchRule `yaml:"branches"`
SmokeTest             string       `yaml:"smoke-test,omitempty"` // a multiline bash script
Library               bool         `yaml:"library,omitempty"`
// not updated when true
Skip bool …
```
=> update example rule

configs/example-rules-configmap.yaml
Signed-off-by: Xiang Dai <long0dai@foxmail.com>
=> Update rule example

hack/fetch-all-latest-and-push.sh
Ref: https://github.com/kubernetes/org/issues/2231
I need to update this script to automatically derive repos from rules...until then, adding the repo here to ensure it's not missed.
/assign @dims
=> fetch-and-push script: add component-helpers repo

cmd/publishing-bot/config/rules.go
This came up on slack - https://kubernetes.slack.com/archives/C5P3FE08M/p1603386108054700
This PR makes it clearer on how to fix the error.
/assign @dims
=> Update error message for repo order validation

OWNERS
Ref: https://github.com/kubernetes/publishing-bot/pulls?q=is%3Apr+author%3Anikhita+is%3Aclosed+
/cc @sttts @dims @caesarxuchao
=> Add nikhita as approver, move caesarxuchao to emeritus approver

cmd/gomod-zip/zip.go
Currently while zipping modules using the `gomod-zip` tool, if a repo
contains submodules, we include them in the zip archive.
However, when we do a `go mod download`, go skips submodules from the
zip archive. This means that the zip file created using `gomod-zip`
is no longer accurate.
This also causes the following error when go tries to read the zip file
(during `go mod tidy`, etc) and notices submodules in the zip archive:
```
-> unzip /go-workspace/pkg/mod/cache/download/k8s.io/code-generator/@v/v0.0.0-20210126111002-a3ae865d6348.zip: found go.mod file not in module root directory (k8s.io/code-generator@v0.0.0-20210126111002-a3ae865d6348/examples/go.mod)
unzip /go-workspace/pkg/mod/cache/download/k8s.io/code-generator/@v/v0.0.0-20210126111002-a3ae865d6348.zip: found go.mod file not …
```
=> gomod-zip: ignore submodules in zip archive

.gitignore, Makefile
partially fixes: https://github.com/kubernetes/publishing-bot/issues/247
k/test-infra PR to add the prow job: https://github.com/kubernetes/test-infra/pull/21446
=> tests: add makefile rule to run go tests

hack/fetch-all-latest-and-push.sh
```
ls -1 staging/src/k8s.io/
```
=> Update list of repos to copy over

hack/fetch-all-latest-and-push.sh
Ref: https://github.com/kubernetes/org/issues/2713
/assign @dims
=> Add pod-security-admission repo to fetch and push test script

k8s-publishing-bot.md
Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
Needed for kubernetes/k8s.io#1597
=> replacing k/k8s.io links in docs

hack/fetch-all-latest-and-push.sh
=> Drop repos no longer in master (csi-api and node-api)

artifacts/scripts/util.sh
Due to some changes in the release tooling, it is now possible to have
two k/k PRs/commits with the same k/k mainline commit. This causes one of the
k/k commit to not be published.
We manually published this missing commit in the staging repo.
Due to this, the bot now re-publishes commits created after the manually added commit.
If a new branch exists at one of the re-published commits, it leads to
two dst_branch_point_commits.
So, allow specifying a list of k/k commits such that only a single
dst_branch_point_commit is picked for them.
See slack thread for more details - https://kubernetes.slack.com/archives/C2C40FMNF/p1638139647251300
---
Tested a local run with this change, published repos are at https://github.com/prowtest/
Would still love to do a nightly run for this commit.
--- …
=> Choose only one dst branch point commit for specified k/k commits

Dockerfile
https://packages.debian.org/stretch/git shows
=> Update Dockerfile to newest git version for debian:stretch

configs/kubernetes-nightly-configmap.yaml
=> Post results to issues in kubernetes-nightly/kubernetes repo

cmd/validate-rules/main.go, cmd/validate-rules/staging/github_utils.go, cmd/validate-rules/staging/validate.go, go.sum
Tested locally using: `go run -mod=mod k8s.io/publishing-bot/cmd/validate-rules ../kubernetes/staging/publishing/rules.yaml`
=> Check if the directories are actually present in k8s branches

README.md
=> update README to match new scripts

OWNERS_ALIASES
Also, alpha sorts the release-engineering-approvers list
Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>
=> OWNERS_ALIASES: promote palnabarun to a Release Manager

artifacts/scripts/util.sh
Context : https://kubernetes.slack.com/archives/C2C40FMNF/p1652208676507389
=> Look in local cache first and then the normal proxy

cmd/sync-tags/main.go, go.mod, go.sum
Update to the latest version of the dependency.
=> Switch to `github.com/blang/semver/v4`

hack/repos.sh
Related to:
- https://github.com/kubernetes/org/issues/3630
Signed-off-by: Arnaud Meukam <ameukam@gmail.com>
=> Add kms repo tp fetch-push script

hack/repos.sh
This is needed for helper code for the dynamic resource allocation feature. The code will be added in https://github.com/kubernetes/kubernetes/pull/111023
The repo request is in https://github.com/kubernetes/org/issues/3821
=> repos.sh: add dynamic-resource-allocation

.github/dependabot.yml, .github/workflows/golangci-lint.yml, hack/verify-golangci-lint.sh
- update golangci-lint to v1.51.2
/assign @nikhita @dims
=> update golangci-lint to v1.51.2

.golangci.yml, cmd/gomod-zip/zip.go, cmd/init-repo/main.go, cmd/publishing-bot/config/rules.go, cmd/publishing-bot/github_test.go, cmd/publishing-bot/log_builder.go, cmd/publishing-bot/log_builder_test.go, cmd/publishing-bot/main.go, cmd/publishing-bot/publisher.go, cmd/publishing-bot/publisher_logger.go, cmd/publishing-bot/publisher_logger_test.go, cmd/publishing-bot/server.go, cmd/sync-tags/gomod.go, cmd/sync-tags/main.go, cmd/update-rules/main.go, cmd/validate-rules/staging/github_utils.go, pkg/git/mapping.go, pkg/golang/install.go
- Fix lints and update golanci-lint config
=> Fix lints and update golanci-lint config

cmd/publishing-bot/main.go
This is required for the CI, since we need to know the exit status of the publisher run. Else the publishing bot always exits with zero, irrespective of whether the run was successful or not.
Fixes issue where the bot exits with 0 , even if the publishing fails. . [Ref](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/publishing-bot/324/pull-publishing-bot-test-kubernetes-master/1643643805510930432#1:build-log.txt%3A801)
=> return the correct exit code when publisher fails

hack/repos.sh
ref: https://github.com/kubernetes/org/issues/4313
=> repos.sh: add endpointslice repo

README.md
Fixing the 404 link in README.md
cc @kubernetes/release-managers
=> Fix link to production.md

artifacts/scripts/util.sh
Fixes https://github.com/kubernetes/publishing-bot/issues/214
This is the same logic used to prune unused replace directives from the main kubernetes/kubernetes repo at https://github.com/kubernetes/kubernetes/blob/master/hack/update-vendor.sh#L355-L361
/hold for testing
=> Prune unused replace directives

cmd/sync-tags/gomod.go
Follow up to https://github.com/kubernetes/publishing-bot/pull/415
There's a go-based step that adds semver tags that is adding back the replace directives.
Logs from this are seen in https://pastebin.com/raw/4ydkDMsY (for the 1.30.0-rc.0 tag cut)
This PR also drops `replace` when cutting tagged releases in the go tool (best reviewed without whitespace - https://github.com/kubernetes/publishing-bot/pull/416/files?w=1)
/cc @thockin @dims
=> Drop replace directives on tagged versions

hack/repos.sh
Refers to https://github.com/kubernetes/org/issues/4805
Needs https://github.com/kubernetes/kubernetes/pull/123797 
/hold
=> Add `cri-client` repository

hack/repos.sh
See https://github.com/kubernetes/org/issues/5224
=> Add externaljwt repo
