kubernetes/publishing-bot

- artifacts/scripts/initialize_repos.sh
- cmd/publishing-bot/github.go
- cmd/publishing-bot/github_test.go
- cmd/publishing-bot/main.go
If the github API returns error when updating the issue, this is not critical for the bot itself. We have other monitoring mechanism (healthz) in place.
> With interval != 0 don't be fatal on Github API errors

- artifacts/scripts/publish_api.sh
- artifacts/scripts/publish_apiextensions_apiserver.sh
- artifacts/scripts/publish_apimachinery.sh
- artifacts/scripts/publish_apiserver.sh
- artifacts/scripts/publish_client_go.sh
- artifacts/scripts/publish_code_generator.sh
- artifacts/scripts/publish_kube_aggregator.sh
- artifacts/scripts/publish_metrics.sh
- artifacts/scripts/publish_sample_apiserver.sh
- artifacts/scripts/publish_sample_controller.sh
- artifacts/scripts/publish_template.sh
- artifacts/scripts/util.sh
- cmd/collapsed-kube-commit-mapper/main.go
- cmd/publishing-bot/config/config.go
- cmd/publishing-bot/healthz.go
- cmd/publishing-bot/main.go
- cmd/publishing-bot/publisher.go
- cmd/sync-tags/main.go
- configs/example-configmap.yaml
- configs/kubernetes-configmap.yaml
- configs/kubernetes-nightly-configmap.yaml
- pkg/git/kube.go
- pkg/git/mapping.go
Reopened https://github.com/kubernetes/publishing-bot/pull/14 seems like GH screwed up or wrong rebase...
his pull attempts to remove all hardcoded kube variables which should allow to use the publisher bot for repositories other than kubernetes/kubernetes.
The defaulting should be preserved, so if SourceRepo is not specified it will default to "kubernetes", thus no changes in how the publisher bot is currently deployed are needed.
> Remove hardcoded kube

- Makefile
- README.md
- artifacts/manifests/podspec.yaml
- cmd/publishing-bot/config/config.go
- cmd/publishing-bot/config/rules.go
- cmd/publishing-bot/main.go
- cmd/publishing-bot/publisher.go
- configs/example-rules-configmap.yaml
- configs/kubernetes-rules-configmap.yaml
The second commit removes hard-coded Kubernetes rules and move them into a separate YAML file that has to be provided for the publishing-bot via `--rules-file` argument. This argument is required.
This can be either a local filesystem path or an URL form (for easier "fetch from repo directly ;)")...
Other changes:
* Moved the `SkippedSourceBranches` into the rules config
* Removed `./` defaulting for the destination directory
Original rules before this change are available under `cmd/publisher-bot/config/rules_example.yaml`.
> Externalize the rule definition into a YAML file

- cmd/publishing-bot/config/rules.go
@sttts critical fix :( Without this it will always fallback to downloading from URL which will result in 0 rules.
> fix rule loading

- artifacts/scripts/util.sh
If a commit only included godep changes, fix-godeps might make it empty which is ok.
This happened yesterday due to a merge of the apiserver release-1.10 branch with master that had no changes other than godep for k8s.io/apiserver.
> Allow fix-godeps to make commits empty

- artifacts/scripts/util.sh
Before this the space-sparated list of patterns came out as one string, e.g. "'BUILD */BUILD'",
although "'BUILD' '*/BUILD'" is correct.
> Fix delete pattern escaping in filter-branch

- artifacts/scripts/util.sh
Now we get ugly re-indention commit in certain situation. Godeps.json should always be indented with tabs.
> Indent godep output with tabs

- Gopkg.lock
- Gopkg.toml
- cmd/publishing-bot/publisher.go
- cmd/publishing-bot/publisher_logger.go
- vendor/gopkg.in/natefinch/lumberjack.v2/.gitignore
- vendor/gopkg.in/natefinch/lumberjack.v2/LICENSE
- vendor/gopkg.in/natefinch/lumberjack.v2/README.md
- vendor/gopkg.in/natefinch/lumberjack.v2/chown.go
- vendor/gopkg.in/natefinch/lumberjack.v2/chown_linux.go
- vendor/gopkg.in/natefinch/lumberjack.v2/lumberjack.go
Logs are in `<repoBasePath>/run.log`, rotated on each run, kept for 7 days.
> Keep 7 days full log history in (rotated) run.log

- cmd/publishing-bot/publisher.go
Fixes https://github.com/openshift/origin/issues/20144
> Replace non-existing clone flag --no-tags in git 2.1.4 with bash tag removal

- Dockerfile
The publishing bot is currently broken because `strings.Builder is undefined`: https://github.com/kubernetes/kubernetes/issues/56876#issuecomment-408741947.
`strings.Builder` was introduced in Go 1.10. We use 1.10.2 in k/k (https://github.com/kubernetes/kubernetes/pull/63412, https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#external-dependencies).
This PR updates the go version to 1.10.2 for publishing bot so that it starts working again.
> Update to go 1.10.2

- configs/kubernetes-rules-configmap.yaml
We don't support anything equal or older than 1.8. Go 1.10 is not compatible with v4.0.0 anymore, link errors.
> Disable publishing of 1.8 and older

- Dockerfile
- cmd/init-repo/main.go
- cmd/publishing-bot/config/rules.go
- cmd/publishing-bot/publisher.go
- cmd/publishing-bot/publisher_test.go
- configs/kubernetes-rules-configmap.yaml
Kube 1.9 and 1.10 need Go 1.9, especially because go vet was extended in Go 1.10. So we better make this configurable.
> Add branch rule go version value

- README.md
- artifacts/scripts/construct.sh
- artifacts/scripts/util.sh
- cmd/init-repo/main.go
- cmd/publishing-bot/config/config.go
- cmd/publishing-bot/main.go
- cmd/publishing-bot/publisher.go
- cmd/publishing-bot/server.go
In case people are running github on-premise, they should be able
to tweak the github address.
the second case is: people might not be using the traditional name
convention like github.com/xxx/yyy as the package base, we should
allow them to specify the package name when cloning the code into
GOPATH.
> cmd/*: add github-host and package flag

- cmd/publishing-bot/log_builder.go
- cmd/publishing-bot/publisher_logger.go
- cmd/publishing-bot/publisher_logger_test.go
resolving bad format lines in logs:
```
+ read dep branch
+ jq '.Deps |= map(select(.ImportPath | (startswith("k8s.io/client-go/") or . == "k8s.io/client-go") | not))' Godeps/Godeps.json
+ indent-godeps
+ unexpand --first-only --tabs=2
+ mv Godeps/Godeps.json.clean Godeps/Godeps.json
R+u necho 'Running godep restore.'
+ godepn restore
ing godep restore.
+ checkout-deps-to-kube-commit Kubernetes-commit apimachinery:master,api:master
+ local commit_msg_tag=Kubernetes-commit
+ deps=()
```
`cmd.Stdout` and `cmd.Stderr` is writting logs per chars, which is the cause of bad outputting as above shown. so we use a `lineWriter` to buffer chars and flush them on `\n`. and a `syncWriter` will prevent dirty write into `bytes.Buffer` because it's not thread-safe.
> Tighten log stdout/err order via lineWriter & syncWriter

- cmd/init-repo/main.go
the cmd to install go version should setup a dir explictly, or it
would fail like `chdir /go-workspace/x: no such file or directory`.
1. `run` setup `Dir` to be `BaseRepoPath` if it is empty at https://github.com/kubernetes/publishing-bot/blob/master/cmd/init-repo/main.go#L255
1. the invocation of [installGoVersion](https://github.com/kubernetes/publishing-bot/blob/master/cmd/init-repo/main.go#L137) sits before the [mkdir of BaseRepoPath](https://github.com/kubernetes/publishing-bot/blob/master/cmd/init-repo/main.go#L145)
> init-repo: set Dir for go installation

- artifacts/scripts/construct.sh
- cmd/publishing-bot/config/rules.go
- cmd/publishing-bot/publisher.go
The `skip-tags: true` option in configuration will prevent the publisher bot from synchronizing the repository tags in case the tags are not required.
> allow to skip tag synchronization

- artifacts/scripts/construct.sh
Running `git gc --auto` should speed up the sync a little and keep the repository in clean state.
> run git gc --auto before syncing repos

- configs/kubernetes-rules-configmap.yaml
- hack/fetch-all-latest-and-push.sh
We have a new https://github.com/kubernetes/csi-api repo that should be populated from https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/csi-api
I would like to turn on auto publishing.
/assign @sttts
> Add csi-api repo to publish bot

- artifacts/scripts/util.sh
In the kube-proxy staging dir the Godeps/README was forgotten originally and added in a later PR. But our godep run in the bot creates it and we left it in the working dir, making the cherry-pick which adds the file fail.
> Delete new Godeps file not on the branch

- cmd/publishing-bot/publisher.go
- `repo.Branches()` only return local branches, but we have to loop over remote origin branches.
- We stored only the master head during publishing. Though the branch head is what counts. This PR fixes this.
> Fix source repo remote branch loop

- configs/kubernetes-rules-configmap.yaml
It had the staging dir of the scheduler.
> Fix kube-controller-manager repo to point to its staging dir

- cmd/publishing-bot/publisher.go
Go-git is strict about ref names. It does not prepend `refs/heads/` automatically. So this PR adds that.
> Fix go-git ref name

- cmd/publishing-bot/publisher.go
We switch to refs/heads/branch like branch names in https://github.com/kubernetes/publishing-bot/pull/106, but forgot to use the short name as key for the branch name hash map.
> Fix branch-name-hash map to be used on publish

- configs/kubernetes-rules-configmap.yaml
publishing-bot is currently broken: https://github.com/kubernetes/kubernetes/issues/56876
https://github.com/kubernetes/kubernetes/pull/68579 added apiextensions-apiserver as a dependency to csi-api but it is not listed as a dependency here, which breaks publishing-bot while reconstructing godeps.json.
This is the relevant part of the error log:
```sh
++ git commit-tree -p 2966180a4e54fab57c98153a33cf018cc4017ba3 -p HEAD -m 'Merge pull request #68579 from verult/adc-crd-access
Updating CSI e2e test to create CSI CRDs
...
+ update_full_godeps apimachinery:master,api:master,client-go:master k8s.io true Kubernetes-commit
+ local deps=apimachinery:master,api:master,client-go:master
+ local base_package=k8s.io
+ local is_library=true
+ local commit_msg_tag=Kubernetes-commit
+ …
```
> Add apiextensions as a dependency to csi-api

- configs/kubernetes-rules-configmap.yaml
- hack/fetch-all-latest-and-push.sh
Reverts kubernetes/publishing-bot#89
The target repository is not ready. It has to be empty. And the publishing-bot needs permissions, compare https://github.com/kubernetes/org/issues/56#issue-356711512.
> Revert "added bootstrap repo."

- .travis.yml
- cmd/init-repo/main.go
- configs/kubernetes-rules-configmap.yaml
Also update the go versions of:
- v1.11 branch to 1.10.2
- v1.12 branch to 1.10.4
Ref:
- v1.11 used go version 1.10.2: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#external-dependencies
- v1.12 used go version 1.10.4: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#external-dependencies
- Bump of go version from 1.10.4 to 1.11.1 on k/k master: https://github.com/kubernetes/kubernetes/pull/69386
> Bump default go version to 1.11.1

- artifacts/scripts/util.sh
Handling merges on feature branches is tricky, especially when the feature branch
is degenerated to single commits on the filtered mainline. Here were add such a
merge commit that is very seldom as non-overlapping feature branches with
intermediate master merges do not happen often.
The respective merge is from https://github.com/kubernetes/kubernetes/pull/69946.
> Handle degenerated non-mainline merge

- artifacts/scripts/util.sh
Handling merges on feature branches is tricky, especially when the feature branch
is degenerated to single commits on the filtered mainline. Here were add such a
merge commit that is very seldom as non-overlapping feature branches with
intermediate master merges do not happen often.
The respective merge is from https://github.com/kubernetes/kubernetes/pull/69946.
> Handle degenerated non-mainline merge - part 2

- artifacts/scripts/construct.sh
If a repo contains `.gitattributes` files and contains special attributes for line endings, they are not respected while fetching using go-git  because it doesn't support `.gitattributes`. So default configuration values are followed. This leads to a dirty workspace.
To avoid this, we need to instruct git to not attempt any line ending conversions. The only way to override the config in `.gitattributes` files is through a `.git/info/attributes` file
This PR adds such a file and prevents any end-of-line conversions.
---
Ref: https://git-scm.com/docs/gitattributes
> When deciding what attributes are assigned to a path, Git consults $GIT_DIR/info/attributes file (which has the highest precedence), .gitattributes file in the same directory as the path in question, and its parent directories …
> Override end-of-line attributes in gitattributes files

- cmd/init-repo/main.go
Ref: https://github.com/kubernetes/kubernetes/pull/70665
/assign @sttts
> Bump default go version to 1.11.2

- configs/kubernetes-rules-configmap.yaml
Ref: https://groups.google.com/d/topic/kubernetes-dev/8D_ea0xw3BQ/discussion
1.13 branch has been created in k/k and with that we stop supporting 1.9 and older.
/assign @sttts
> Add 1.13 branches and disable publishing of 1.9

- artifacts/scripts/construct.sh
Fix bug: shell syntax error, ${1-k8s.io}  -> ${1:-k8s.io}
> Fix bug: shell syntax error

- configs/kubernetes-rules-configmap.yaml
- hack/fetch-all-latest-and-push.sh
- Repo creation request: https://github.com/kubernetes/org/issues/38
- Repo with initial empty commit: https://github.com/kubernetes/node-api
- PR against test-infra for branch protection: https://github.com/kubernetes/test-infra/pull/10194
- Dependencies: https://github.com/kubernetes/kubernetes/blob/31e2ba9f38bf950476fcaab01f7b0f9f5baf9fe7/staging/src/k8s.io/node-api/Godeps/Godeps.json
/cc @tallclair @sttts  
/assign @sttts
> Add node-api repo

- configs/kubernetes-rules-configmap.yaml
- hack/fetch-all-latest-and-push.sh
- Repo creation request: https://github.com/kubernetes/org/issues/321
- Repo with initial empty commit: https://github.com/kubernetes/csi-translation-lib
- PR against test-infra for branch protection: https://github.com/kubernetes/test-infra/pull/10676
- PR for staging against k/k: https://github.com/kubernetes/kubernetes/pull/72770
- Dependencies: As per the [`Godeps.json`](https://github.com/kubernetes/kubernetes/blob/ab2e26386f9a309feda55e735b28db8919921c3f/staging/src/k8s.io/csi-translation-lib/Godeps/Godeps.json) in the PR, the csi-translation-lib depends on `api` and `apimachinery` and no other staging repos depend on it.
/cc @ddebroy @sttts 
/assign @sttts 
/hold 
until:
> Add csi-translation-lib repo

- configs/kubernetes
The linker gets killed due to memory with 1.5Gi.
> Increase memory limits to survive smoke-test

- configs/kubernetes-rules-configmap.yaml
Both (will) use component-base. apiextensions-apiserver even does today (and publishing breaks).
> rules: add component-base dep to apiextensions-apiserver and kubelet

- pkg/golang/install.go
Ref: https://github.com/kubernetes/kubernetes/pull/74632
/cc @dims @sttts
> Bump default go version to 1.12

- hack/fetch-all-latest-and-push.sh
Ref:
- Repo creation request: https://github.com/kubernetes/org/issues/642
- Repo with initial empty commit: https://github.com/kubernetes/cri-api
- PR against test-infra for branch protection: https://github.com/kubernetes/test-infra/pull/11941
- PR for to add repo to staging against k/k: https://github.com/kubernetes/kubernetes/pull/75531
- PR for updating publishing-bot rules against k/k: https://github.com/kubernetes/kubernetes/pull/75531
/hold
This needs to be added to staging and the rules need to be updated
/assign @dims @sttts
> Add new staging repo: cri-api

- .editorconfig
- Dockerfile
- Makefile
- README.md
- artifacts/scripts/construct.sh
- artifacts/scripts/util.sh
- cmd/godeps-gen/main.go
- cmd/init-repo/main.go
- cmd/publishing-bot/config/rules.go
- cmd/publishing-bot/publisher.go
This removes godeps support and adds generation of go.mod+sum. No vendor/ is generated anymore.
In parallel, there is a godeps branch forked off before this PR. We will keep running a second instance for all pre-1.15 versions.
> go-mod support

- hack/fetch-all-latest-and-push.sh
Ref:
- Repo creation request: https://github.com/kubernetes/org/issues/719
- Repo with initial empty commit: https://github.com/kubernetes/legacy-cloud-providers
- PR against test-infra for branch protection: https://github.com/kubernetes/test-infra/pull/12220
- PR for to add repo to staging against k/k: https://github.com/kubernetes/kubernetes/pull/75910
- PR for updating publishing-bot rules against k/k: https://github.com/kubernetes/kubernetes/pull/75910/commits/8e508598982bbd9b392eaf7b0aaaed6f833a9e94#diff-91f67bda331c4de19a3b70c86f69a080
- @kubernetes/stage-bots team has admin access to the repo :heavy_check_mark: 
/hold
Needs to be added to staging, rules need to be updated and branch protection PR needs to be merged.
/cc @dims @sttts @andrewsykim 
/assign @sttts
> Add new staging repo: legacy-cloud-providers

- README.md
- k8s-publishing-bot.md
For https://github.com/kubernetes/k8s.io/issues/183
The file should probably be renamed but I can't think of anything better/apt right now.
/kind documentation
/assign @dims @sttts
> Add docs about running publishing-bot in CNCF infra

- pkg/golang/install.go
Ref: https://github.com/kubernetes/kubernetes/pull/77528
Related https://github.com/kubernetes/kubernetes/pull/77805
/assign @sttts @dims
> Bump default go version to 1.12.5

- artifacts/scripts/util.sh
When `f_latest_merge_commit` is a direct descendant of `f_latest_branch_point_commit` - this can occur while doing a `git merge --no-ff` when it should have been a fast forward merge - there will be no diff between them. Applying an empty patch will give an error.
So, apply the patch only if it exists and allow an empty commit so that the go.mod changes can be squashed
with this commit later, if needed.
---
In the current case:
- `f_latest_merge_commit` is `0b6b7933b323bfa1127d27eb580ca17a7bd66ae1` - "Merge branch 'master' of https://github.com/kubernetes/kubernetes into fix-golint-utils-bandwith"
- `f_latest_branch_point_commit` is `5ee4f206df86965a75ed5aaf880f98161c70a9c1` - "Merge pull request #75849 from jpbetz/pagination-podgc"
<details open>
<summary>Relevant part of the …
> Don't apply empty patch when merge commit is direct descendant of branch point commit

- hack/fetch-all-latest-and-push.sh
For https://github.com/kubernetes/kubernetes/pull/77762. This will actually switch on the publishing-bot for the kubectl repo.
/hold
until https://github.com/kubernetes/kubernetes/pull/77762 and https://github.com/kubernetes/test-infra/pull/12794 have merged
/cc @seans3 @dims @sttts 
/assign @sttts
> Add new staging repo: kubectl

- Dockerfile
- Makefile
- artifacts/scripts/construct.sh
sync-tags is [disabled](https://github.com/kubernetes/publishing-bot/commit/31e2757859d1f3d65a8593e502c5f0880ad105bc) for the main publishing-bot because gomodules
support hasn't been implemented yet. But it remained enabled for the
godeps branch, which meant that tagging still took place but didn't
include go.mod files at all.
This commit removes sync-tags support from the godeps branch, so that it
can be enabled for the main publishing-bot from the master branch later
(after gomodules support has been added).
Relevant slack thread - https://kubernetes.slack.com/archives/C2C40FMNF/p1560158651078000
/assign @sttts @dims
> Enable sync-tags only for main publishing-bot

- artifacts/scripts/construct.sh
- cmd/sync-tags/godeps.go
- cmd/sync-tags/gomod.go
- cmd/sync-tags/main.go
This commit adds gomodules support for tagging (to sync-tags) to make sure
that kube dependencies point to the commit sha at the relevant tag in go.mod.
If the repo at the tag has a go.mod file, sync-tags pins the dependencies
at the pseudoversion pointing to the tag and packages up into the local
go mod cache, so that it can be downloaded and used by `go mod tidy`.
After that, godeps-gen is used to generate Godeps.json from the go.mod file.
If the repo at the tag does not contain a go.mod file, sync-tags directly
updates Godeps.json to point to the commit sha at the tag (old behaviour).
/cc @sttts @dims @liggitt 
/assign @sttts
> sync-tags: add gomodules support

- Dockerfile
- Makefile
- artifacts/scripts/util.sh
- cmd/gomod-zip/zip.go
- cmd/sync-tags/gomod.go
- cmd/sync-tags/main.go
This PR has the following changes:
- Display the error that might occur while running a `exec.Command`.
- Run `go mod download` before packaging up a dependency _and_ before updating the require and replace directives. This will help in avoiding packaging up, when the pseudo version is the same but we don't have it in the local cache.
- Fix the git command used for pseudo version calculation (#186)
- Publish all tags, not just alpha ones.
- Add a new go binary `gomod-zip` for creating the zip file that would have the same hash as that of the zip file if it were downloaded by `go mod download`. The zip file created by gomod differs from the former:
- there are some extra normalizations: not considering anything in vendor, making sure we don't have directories in the file archive. These …
> Fix go mod publishing

- Makefile
- cmd/godeps-gen/main.go
- cmd/init-repo/main.go
The year is the year the files were authored in.
/shrug
/assign @sttts
> Add missing copyright boilerplate headers

- cmd/init-repo/main.go
Since we decided not to replace bitbucket with github for 1.12 (https://github.com/kubernetes/kubernetes/pull/79525), this will be needed to fix the currently broken godeps-publishing-bot (and to sync/publish the `release-1.12` branch for all repos).
Note that this does not fix the publishing of the `v1.12.10` tag because that's done by `sync-tags` by the bot running against the `master` branch. Created https://github.com/kubernetes/publishing-bot/pull/192 for it.
The godeps-publishing-bot gives this error (https://github.com/kubernetes/kubernetes/issues/75960) right now:
```
+ echo 'Running godep restore.'
+ godep restore
godep: error downloading dep (bitbucket.org/ww/goautoneg): https://api.bitbucket.org/1.0/repositories/ww/goautoneg: 410 Gone
godep: Error downloading some deps. …
```
> [godeps]  Use kubernetes' forked version of godep 

- Dockerfile
- Makefile
- artifacts/scripts/construct.sh
Reverts https://github.com/kubernetes/publishing-bot/pull/183. https://github.com/kubernetes/publishing-bot/pull/183 wasn't deployed, which is good. :)
/assign @sttts
> Run sync-tags on godeps branch

- pkg/golang/install.go
Ref: https://github.com/kubernetes/kubernetes/pull/79966
/assign @sttts
> Bump default Go version to 1.12.7

- configs/kubernetes
Ref: https://github.com/kubernetes/k8s.io/pull/282
Will redeploy once this gets merged.
Note: we will have to repush the image every 2 months or so (https://github.com/kubernetes/k8s.io/pull/297). Something tells me that we'll end up doing that anyway. :upside_down_face: 
/assign @sttts @dims
> Use gcr.io/k8s-staging-publishing-bot for storing image

- pkg/golang/install.go
Bump default Go version to 1.12.8
Ref: https://github.com/kubernetes/kubernetes/issues/79912
/assign @sttts
> Bump default Go version to 1.12.8

- pkg/golang/install.go
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
ref: https://github.com/kubernetes/kubernetes/pull/81489
> Bump default Go version to 1.12.9

- artifacts/scripts/util.sh
- cmd/sync-tags/gomod.go
Ref: https://github.com/kubernetes/kubernetes/issues/83761
If a dependency is re-tagged after the dependency is updated in k/k, the
hash in go.sum in k/k will point to the old tag.
When we run `go mod download` in the publishing-bot, the bot currently
downloads directly from github.com. Since the dependency was re-tagged,
the downloaded hash points to the new tag and is no longer equal to
the old hash in go.sum. This leads to a "checksum mismatch error".
Reverting the bad dependency update in k/k won't help with the
publishing-bot because we check if go.mod needs update after each commit.
To fix the bot while encountering such "bad" changes, this commit uses
proxy.golang.org as GOPROXY while running `go mod download` since
proxy.golang.org caches content and the old hash still exists …
> Use proxy.golang.org for go mod download

- pkg/golang/install.go
Ref: https://github.com/kubernetes/kubernetes/pull/82809
/assign @sttts
> Bump default Go version to 1.13.4

- configs/kubernetes-nightly
If we use `sttts/k8s-publishing-bot-nightly`, @sttts would need to push the image everytime.
/hold
I'm not sure if we want to have the nightly version in the "official" gcr staging repo, so adding an explicit hold for this. If we don't want to have it there, we can always specify a personal docker repo while deploying the nightly bot too.
/assign @dims @sttts 
fyi @liggitt
> Use gcr.io/k8s-staging-publishing-bot for nightly

- hack/fetch-all-latest-and-push.sh
`git fetch --tags` is needed to fetch all tags and `git push --atomic`
will help in ensuring that we don't end up selectively pushing tags.
/cc @dims @liggitt @sttts
> Update fetch and push commands in helper script

- Gopkg.lock
- artifacts/scripts/construct.sh
- cmd/sync-tags/gomod.go
- cmd/sync-tags/main.go
- vendor/github.com/blang/semver/.travis.yml
- vendor/github.com/blang/semver/LICENSE
- vendor/github.com/blang/semver/README.md
- vendor/github.com/blang/semver/go.mod
- vendor/github.com/blang/semver/json.go
- vendor/github.com/blang/semver/package.json
- vendor/github.com/blang/semver/range.go
- vendor/github.com/blang/semver/semver.go
- vendor/github.com/blang/semver/sort.go
- vendor/github.com/blang/semver/sql.go
For https://github.com/kubernetes/kubernetes/issues/84608
Implements changes to the go modules KEP made in
https://github.com/kubernetes/enhancements/pull/1350.
This commit updates sync-tags to publish `v0.x.y` tags for corresponding
`v1.x.y` Kubernetes tag. The old `kubernetes-1.x.y` tags are still also
published. Both `kubernetes-1.x.y` and `v0.x.y` point to the same sha.
For `v0.x.y`:
- At this tag, `go.mod` uses `v0.x.y` tags for dependencies.
- When this tag is manually specified in a `go.mod` file, it will be
retained as `v0.x.y`.
For `kubernetes-1.x.y`:
- At this tag, `go.mod` uses `v0.x.y` tags for dependencies. Note: this
differs from the previous way, where pseudoversions were used.
- When this tag is manually specified in a `go.mod` file, go will resolve
it to the appropriate …
> sync-tags: add support for v0.x.y tags

- Dockerfile
- cmd/sync-tags/gomod.go
Fixes https://github.com/kubernetes/publishing-bot/issues/217.
> sync-tags: on volume recreation tags might only exist as origin/<tag>

- k8s-publishing-bot.md
The godeps instance of the bot has now been removed. This instance was
only used for Kubernetes versions <=1.14, which are not
supported anymore.
The final patch release for 1.14 was in early December, so we can now be
sure that we don't need this instance anymore.
/assign @dims
> Remove note about godeps instance of the bot

- k8s-publishing-bot.md
For https://github.com/kubernetes/k8s.io/issues/503
Bot has been migrated to the `aaa` cluster. 
/assign @dims
> Update docs after migration to aaa cluster

- artifacts/scripts/util.sh
`sed -s /^/"${base_package}\/"/` only works when there is no `/`
in `${base_package}`. While this is true for `k8s.io`, this is not
necessary true for downstream repositories.
Here is the error message when `${base_package}` is `tess.io/ebay`:
```console
++ echo api:master
++ tr , '\n'
++ sed -e 's/:.*//' -e 's/^/tess.io/ebay\//'
++ paste -sd , -
sed: -e expression #2, char 14: unknown option to `s'
+ dep_packages=
E0601 19:23:26.812345      12 publisher.go:413] exit status 1
I0601 19:23:26.815109      12 main.go:202] Failed to run publisher: exit status 1
```
Fixes #225.
> scripts: update sed separator to be `,`

- pkg/golang/install.go
Ref:
- https://github.com/kubernetes/kubernetes/pull/88638 updated go to 1.14.4
- https://github.com/kubernetes/kubernetes/pull/92438 contains fixups to move to 1.14.4
I have created https://github.com/kubernetes/publishing-bot/issues/229 to track moving `defaultGoVersion` to the rules file and will work on it after this PR gets merged. I'd prefer merging this for now to fix the bot (it broke down because some repos now require 1.14 specific code):
```
[24 Jun 20 05:55 UTC]: Running smoke tests for branch master
[24 Jun 20 05:55 UTC]: /bin/bash -xec "# assumes GO111MODULE=on\ngo build .\n"
+ go build .
../../../pkg/mod/k8s.io/component-base@v0.0.0-20200624053949-32266bec4512/cli/flag/ciphersuites_flag.go:51:51: undefined: tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 …
```
> Bump default go version to 1.14.4

- cmd/init-repo/main.go
- cmd/publishing-bot/config/rules.go
- pkg/golang/install.go
Today, the `defaultGoVersion` is hardcoded in the publishing-bot. This
means that whenever k/k undergoes a go version bump, we need to manually
update the hardcoded version in the bot.
To ensure that we can bump the go version for publishing-bot along with
other places in k/k, this commit moves `defaultGoVersion` to the rules
file.
This commit introduces the following changes:
- A new optional field `default-go-version` is introduced in the rules
file.
- To avoid breaking existing users, if the `default-go-version` field is
not specified in the rules file, the bot defaults to
`deprecatedDefaultGoVersion` (go 1.14.4). Since go stops supporting
Go 1.x once Go 1.x+2 is released, the defaulting to
`deprecatedDefaultGoVersion` will be removed once go 1.16 is released
and users will be required …
> Move default go version to rules file

- artifacts/scripts/util.sh
If a dependency's look-up table is empty, we will get an error while
trying to read the `kube-commits-${dep}-${branch}` file.
To avoid getting this error, this commit adds a check for the file size
before reading the file.
---
Note to self -  a dependency's look-up table can be empty if it does
not have merge commits in the filtered branch.
This case is possible because:
- `git filter branch` drops fast-forward merges which don't contain
diffs.
- While constructing the tree to create the dropped merge commit, it is
possible that the second parent of the merge commit is also `HEAD`
of the filtered branch. Since both parents would be then be `HEAD`,
we end up with a tree with no merge commits as first parents.
> Skip checkout of deps if their look-up table is empty

- artifacts/scripts/util.sh
Currently, after running `git filter-branch` and constructing dropped
fast-forward merges, we check if there are merge commits in this new
list of commits. Only if there are merge commits, we construct the
look-up table for mapping k/k mainline commits to destination commits.
However, it is not necessary that this new filtered list of commits
should have merge commits. The mapping is from **_k/k's merge commits_** to
first parent commits in the destination repo. The only requirement is
that k/k should have merge commits, requiring merge commits in the
destination repo is not necessary.
We also always need the look-up table to update go.mod files if a repo
is a dependency to another staging repo. The look-up table is also needed
to figure out which commit should be tagged.
We …
> Always create lookup-up table for source-to-dst mapping

- cmd/sync-tags/main.go
In sync-tags, we try to publish corresponding tags for ALL tags in
k/k. This means that even if the repo didn't exist at an old
tag like `v0.10.0-alpha.0`, we still try to publish it.
If the repo is new and has no dependencies, then the published tag
`v0.10.0-alpha.0` will point to an empty repo with an initial
empty commit.
Example - https://github.com/kubernetes/mount-utils/tree/v0.10.0-alpha.0
However, if a repo is new AND has dependencies, we will also try
to update deps in go.mod to point to `v0.10.0-alpha.0`.
But since the repo is empty at this tag, `go mod download` fails
with:
```
go mod download: no modules specified (see 'go help mod download')
```
To fix the error, we need to update go.mod only if the go.mod file
exists.
This commit moves the check for existence of go.mod to …
> sync-tags: update deps only if go.mod exists at tag

- cmd/publishing-bot/config/rules.go
- cmd/publishing-bot/config/rules_test.go
Ref: https://github.com/kubernetes/kubernetes/pull/98572#discussion_r567076244
The current validation fails for the rc tag because go versions
don't follow semver. For example, 1.16rc1 is a valid go version
but the publishing-bot validation fails.
To fix this issue, this commit validates using a regular expression.
Regex is derived from https://github.com/kubernetes-sigs/kubebuilder/blob/3c8e370d49c58179037d69f926318093f82f68d2/pkg/plugins/internal/util/go_version.go#L57.
/assign @dims 
cc @sttts @justaugustus
> rules: fix go version validation

- cmd/publishing-bot/config/rules.go
- cmd/publishing-bot/config/rules_test.go
In the PR to bump the go version to 1.15.10 in the kubernetes/kubernetes repo, the publishingbot failed to validate the go version `1.15.10`, see prwo job: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/100375/pull-publishing-bot-validate/1372599248561901568
```
I0318 17:24:03.759743     155 rules.go:94] loading rules file : /home/prow/go/src/k8s.io/kubernetes/staging/publishing/rules.yaml
I0318 17:24:03.778078     155 rules.go:130] validating repository order
I0318 17:24:03.778167     155 rules.go:152] validating go versions
F0318 17:24:03.778287     155 main.go:35] Invalid rules file "/home/prow/go/src/k8s.io/kubernetes/staging/publishing/rules.yaml": validation errors:
- specified go version 1.15.10 is invalid
```
however this version is a valid one, This PR update the …
> update regex to match some special case (ie 1.15.10)

- cmd/publishing-bot/config/rules.go
- cmd/publishing-bot/publisher.go
Currently, smoke tests are specified for the entire repo and apply to
all branches. However, this leads to problems when a single test cannot
be run across all branches.
For example, the smoke test for client-go uses `go test -mod=mod ./...`.
The `-mod=mod` option is available only from go1.14 and is necessary for
running tests with go1.16 (https://github.com/kubernetes/kubernetes/pull/99674)
client-go `release-1.18` branch uses go1.13.15 which doesn't support the
`-mod=mod` option, so the tests fail.
This commit fixes this issue by additionally allowing to specify smoke
tests per branch. The current option for tests that apply to all
branches is not changed to maintain compatibility.
Note: this issue got triggered because there was a recent change to the
client-go `release-1.18` branch …
> Allow specifying branch-specific smoke tests

- artifacts/scripts/util.sh
[gomod-zip](https://github.com/kubernetes/publishing-bot/tree/master/cmd/gomod-zip) copied go's zip creation code but they had diverged.
due to this, gomod-zip created different zip files in the cache
compared to what go mod download would create (fixed in https://github.com/kubernetes/publishing-bot/pull/254)
From Go 1.15.11 and Go 1.16.3, go automatically derives the ziphash
from the zip file in the cache - https://github.com/golang/go/issues/44812.
This meant that go added incorrect hash values to go.sum because these
were derived from the zip files produced by the diverged gomod-zip code.
So remove go.sum here and regenerate again using go mod download and go mod tidy
to include the right hash values.
Note - this line should be removed after one clean publishing-bot run to be able to …
> util.sh: regenerate go.sum to fix incorrect hash values

- artifacts/scripts/util.sh
This PR contains two fixes/commits. The commit messages have more details.
- Use `GOPRIVATE` before `go mod tidy` to avoid errors like:
```
+ go mod tidy
k8s.io/apimachinery@v0.0.0-20210421190751-2d51b868ae8a: verifying module: k8s.io/apimachinery@v0.0.0-20210421190751-2d51b868ae8a: reading https://sum.golang.org/lookup/k8s.io/apimachinery@v0.0.0-20210421190751-2d51b868ae8a: 410 Gone
server response: not found: k8s.io/apimachinery@v0.0.0-20210421190751-2d51b868ae8a: invalid version: unknown revision 2d51b868ae8a
```
- Remove obsolete `go mod download` before packaging up dependencies into go mod cache. This causes an error if a published go.mod contains an incorrect hash. Removing these lines unblocks publishing a fixed go.mod file.
```
verifying …
```
> Fix more checksum errors

- artifacts/scripts/util.sh
- cmd/sync-tags/gomod.go
- hack/fetch-all-latest-and-push.sh
This PR contains two fixes, the commit messages contain more details.
- The first commit removes go.sum only if it is non-empty. If we remove go.sum if it is empty, it will not be recreated in the next step while running `go mod tidy` and will lead to errors like:
<details><summary>Expand to display error</summary>
```
+ rm go.sum
+ GO111MODULE=on
+ GOPRIVATE=
+ GOPROXY=https://proxy.golang.org
+ go mod download
+ GOPROXY=file:///go-workspace/pkg/mod/cache/download
+ GO111MODULE=on
+ GOPRIVATE=
+ go mod tidy
+ git add go.mod go.sum
+ grep 000000000000 go.sum
grep: go.sum: No such file or directory
+ git-index-clean
+ git diff --cached --exit-code
+ return 1
+ echo 'Committing go.mod'
+ git commit -q -m 'sync: update go.mod'
+ ensure-clean-working-dir
+ git diff HEAD --exit-code
+ '[' true …
```
> Correctly set GOPRIVATE and remove go.sum only if non-empty

- cmd/sync-tags/gomod.go
Like https://github.com/kubernetes/publishing-bot/commit/ecc0e43fc19de91285c051ea3ae5fecca4a38ae8, but for syncing tags.
/hold
running nightly tests
/assign @dims
> sync-tags: remove obsolete go mod download

- artifacts/scripts/util.sh
This reverts commit 070c1b6f9c02f340622a6e002b32bd2443951d0f.
This code removed the remaining `Godeps/Godeps.json` file from published repos. We have had a clean bot run and Godeps has now been [removed from the published repos](https://github.com/kubernetes/client-go/tree/master).
Given that k/k doesn't have Godeps anymore either, it is safe to remove this code from the publishing-bot.
/assign @dims
> Revert "Unconditionally remove Godeps"

- OWNERS
- OWNERS_ALIASES
- SECURITY_CONTACTS
Part of https://github.com/kubernetes/sig-release/issues/1772.
- OWNERS: Generated update via dims/maintainers
**NOTE**: I needed to create a placeholder OWNERS_ALIASES file for the
tool to run successfully.
```console
$(go env GOPATH)/bin/maintainers -f -r kubernetes/publishing-bot
Running script : 12-03-2021 23:54:40
Processing /Users/augustus/prj/k8s/publishing-bot/OWNERS_ALIASES
Processing /Users/augustus/prj/k8s/publishing-bot/OWNERS
Found 0 unique aliases
Found 4 unique users
>>>>> Contributions: 3
>>>>> GitHub ID : Devstats contrib count : GitHub PR comment count
nikhita : 58 : 15
dims : 24 : 16
sttts : 5 : 6
>>>>> Missing Contributions (devstats == 0): 1
"mfojtik"
>>>>> Low reviews/approvals (GH pr comments <= 10 && devstats <=20): 1
"sttts"
Fixing up …
```
> OWNERS: Add Release Engineering reviewers

- Makefile
- cloudbuild.yaml
Part of https://github.com/kubernetes/publishing-bot/issues/272.
- Add GCB config for image building
- cloudbuild.yaml: Use k8s-ci-builder:latest-default
- cloudbuild.yaml: Ensure images are pushed after build
- cloudbuild.yaml: Wire up image tagging
- cloudbuild.yaml: Use IMG_REGISTRY to determine push registry
- cloudbuild.yaml: Drop unnecessary variables
Signed-off-by: Stephen Augustus <foo@auggie.dev>
> Add GCB config for image building

- hack/create-repos.sh
- hack/fetch-all-latest-and-push.sh
- hack/repos.sh
often we add new repos in staging and it's a manual process to create the repositories. let's automate that.
```hack/create-repos.sh kubernetes-nightly```
> Script to fork/create repositories needed by publishing-bot

- .golangci.yml
- cmd/collapsed-kube-commit-mapper/main.go
- cmd/gomod-zip/zip.go
- cmd/init-repo/main.go
- cmd/publishing-bot/config/rules.go
- cmd/publishing-bot/config/rules_test.go
- cmd/publishing-bot/github.go
- cmd/publishing-bot/log_builder.go
- cmd/publishing-bot/log_builder_test.go
- cmd/publishing-bot/main.go
- cmd/publishing-bot/publisher.go
- cmd/publishing-bot/publisher_logger.go
- cmd/publishing-bot/publisher_logger_test.go
- cmd/publishing-bot/publisher_test.go
- cmd/publishing-bot/server.go
- cmd/sync-tags/gomod.go
- cmd/sync-tags/main.go
- cmd/validate-rules/main.go
- cmd/validate-rules/staging/github_utils.go
- cmd/validate-rules/staging/validate.go
- hack/verify-golangci-lint.sh
- pkg/git/mapping.go
- pkg/golang/install.go
Signed-off-by: Stephen Augustus <foo@auggie.dev>
Initial results:
```console
❯ ./hack/verify-golangci-lint.sh
```
<details>
```console
/usr/local/bin/golangci-lint
golangci-lint has version 1.43.0 built from 861262b on 2021-11-02T20:54:42Z
Enabled by your configuration linters:
asciicheck: Simple linter to check that your code does not contain non-ASCII identifiers [fast: true, auto-fix: false]
bodyclose: checks whether HTTP response body is closed successfully [fast: false, auto-fix: false]
deadcode: Finds unused code [fast: false, auto-fix: false]
depguard: Go linter that checks if package imports are in a list of acceptable packages [fast: false, auto-fix: false]
dogsled: Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f()) [fast: true, auto-fix: false]
dupl: …
```
> Lint all the things

- cmd/sync-tags/main.go
- go.mod
- go.sum
- go.mod: Update module to go1.17
- go.mod: renstrom/dedent is now lithammer/dedent
Fixes: https://github.com/kubernetes/publishing-bot/issues/248
/assign @nikhita @liggitt
> go.mod: Update module to go1.17 and fix lithammer/dedent import

- README.md
As proposed by @justaugustus in https://github.com/kubernetes/sig-release/pull/1504#pullrequestreview-810342941, this PR adds instructions for keeping rules up-to-date. The instructions cover what you need to do when adding a new release branch and when updating the Go version.
/assign @justaugustus @cpanato @Verolop
/cc @dims @sttts @nikhita 
cc: @kubernetes/release-engineering
> Add instructions for updating rules

- Makefile
- artifacts/manifests/podspec.yaml
We now manage the Github Token with a `ExternalSecret`:
https://github.com/kubernetes/k8s.io/blob/main/apps/publishing-bot/externalsecrets.yaml.
Manual deployment of it is not longer required.
Signed-off-by: Arnaud Meukam <ameukam@gmail.com>
> Update github token secret

- Dockerfile
- Makefile
- README.md
- cmd/publishing-bot/config/rules.go
- cmd/update-rules/README.md
- cmd/update-rules/main.go
- cmd/update-rules/main_test.go
- cmd/update-rules/testdata/invalid_rules.yaml
- cmd/update-rules/testdata/rules.yaml
- Add `cmd/update-rules` to update publishing-bot rules
- Required flags: `--rules`, `--branch`
- Exports the updated rules to file pointed by `-o` otherwise on prints stdout
- Pin go version provided by `--go` flag else leave the field empty (`omitempty`)
- Refer master branch rule per destination repo to add/update rule for provided branch
```
Usage:  update-rules --branch BRANCH --rules PATH [--go VERSION | -o PATH]
```
- Update rules for branch release-1.21 with go version 1.16.4
```
update-rules -branch release-1.21 -go 1.16.4 -rules /go/src/k8s.io/kubernetes/staging/publishing/rules.yaml
```
- Update rules using URL to input rules file
```
update-rules -branch release-1.21 -go 1.16.4 -rules https://raw.githubusercontent.com/kubernetes/kubernetes/master/staging/publishing/rules.yaml …
```
> Add update-rules command to update publishing-bot rules

- artifacts/scripts/construct.sh
We perform many history altering commands in the publishing-bot,
which can lead to unreachable loose objects.
`git gc --auto` will try to prune these loose objects. By default, it
will prune loose objects older than 2 weeks. It looks like we have a lot
of unreachable loose objects, so pruning objects older than 2 weeks
still leaves behind enough loose objects ([ref](https://github.com/kubernetes/kubernetes/issues/56876#issuecomment-1120575224)):
```
Running garbage collection.
+ echo 'Running garbage collection.'
+ git gc --auto
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
error: The last gc run reported the following. Please correct the root cause
and remove .git/gc.log.
Automatic cleanup will not be performed until the …
```
> construct.sh: git prune more aggressively to remove unreachable objects

- Makefile
- cloudbuild.yaml
The bot uses the `k8s-publishing-bot` image, not the `publishing-bot` image - https://github.com/kubernetes/publishing-bot/blob/master/configs/kubernetes#L1
So we should update the GCB config to match what the bot uses.
/assign @dims
> Update image for automatic image publishing

- artifacts/manifests/storage-class.yaml
updating deprecated storage.k8s.io/v1beta1 StorageClass to v1
Signed-off-by: Akhil Mohan <akhilerm@gmail.com>
> chore: update StorageClass to v1

- OWNERS
- OWNERS_ALIASES
- enable owners aliases and update sig release/release-engineer group
This was supposed to be enabled/cleanup after release 1.24 :)
/assign @justaugustus @saschagrunert @nikhita @dims
> enable owners aliases and update sig release/release-engineer group

- artifacts/scripts/util.sh
Fixes https://github.com/kubernetes/publishing-bot/issues/304
Ref: https://github.com/kubernetes/kubernetes/issues/113366, https://github.com/kubernetes/kubernetes/pull/114829
I haven't had the chance to do a test run of the bot to verify this but can reproduce this locally using:
1. Clone the https://github.com/kubernetes/kube-aggregator repo (the publishing-bot fails while publishing this repo).
2. Run `go mod edit -require=golang.org/x/oauth2@v0.3.0`. It's not an exact representation of what the bot does since it doesn't update k8s deps but it's enough to reproduce the error.
3. Run `go mod tidy`. We'll see a failure:
```
k8s.io/kube-aggregator/pkg/cmd/server imports
k8s.io/apiserver/pkg/server/options imports
k8s.io/apiserver/pkg/storage/storagebackend/factory imports …
```
> go get explicit versions to avoid ambiguous imports

- artifacts/scripts/util.sh
This reverts commit a329b530fc789a826f7d08776eeef14547bb2a19.
xref https://github.com/kubernetes/publishing-bot/pull/305#discussion_r1062414743
Let's probably do a complete nightly run first.
> Revert "go get explicit versions to avoid ambiguous imports"

- artifacts/scripts/util.sh
This reverts commit 2877cecb3082ace454ea5edf37b5ad12b0e500e3.
Reverts https://github.com/kubernetes/publishing-bot/pull/308.
The revert should only be merged after https://github.com/kubernetes/kubernetes/pull/114829 gets published, so:
/hold
> Revert "Temporarily go get explicit versions to avoid ambiguous imports"

- OWNERS
We desperately need more reviwers for the publishing-bot.
@akhilerm has been active with the publishing-bot and has been creating non-trivial PRs - https://github.com/kubernetes/publishing-bot/pulls?q=+is%3Apr+author%3Aakhilerm+
Additionally, he is also authoring the publishing-bot instance/code for containerd. He has also volunteered to help maintain the publishing-bot in the future.
/hold
/assign @dims 
/cc @dims @akhilerm 
@akhilerm  -- please comment here if this sounds good to you!
> Add akhilerm as reviewer

- test/k8s-gen-bot-config.sh
- test/run-bot-local.sh
- test/k8s-gen-bot-config.sh generates the config and rules to run the bot on k/k master branch
- test/run-bot-local.sh runs the bot using the config and rules generated using the *-gen-bot-config.sh script
> add scripts to run/test publishing-bot locally

- Dockerfile
- artifacts/scripts/util.sh
- update docker base image from stretch to bullseye, as stretch packages have been archived
- git version is also updated with the current version available in bullseye
- remove `-b` flag in `look` command since binary search is the default method used now.
Fixes: #350
> update docker base image to bullseye

- artifacts/scripts/construct.sh
- artifacts/scripts/push.sh
- artifacts/scripts/util.sh
- cmd/publishing-bot/publisher.go
containerd uses `/` in branch name like `release/1.6`, `release/1.7` etc.  To support this use case, names containing `/` which is a directory separator in linux should be handled separately.
The "/" in destination branch name needs to be treated differently as the branch name is used as suffix in certain file names. Therefore "/" is replaced with "_" wherever the files are created/accessed using the branch name suffix.
Part of #320
> enable support for "/" in branch name

- artifacts/scripts/construct.sh
- artifacts/scripts/util.sh
- cmd/init-repo/main.go
- cmd/publishing-bot/config/config.go
- cmd/publishing-bot/main.go
- cmd/publishing-bot/publisher.go
- cmd/update-rules/main.go
currently only master branch is supported as the default branch. This change adds a new `git-default-branch` in the config that can be used to set the default branch to be used while running `publishing-bot` and `init-repo` commands
Part of #320
> add support for configuring default git branch

- .github/dependabot.yml
- .github/workflows/golangci-lint.yml
- .golangci.yml
- cmd/publishing-bot/main.go
- cmd/publishing-bot/server.go
- hack/verify-golangci-lint.sh
- pkg/golang/install.go
- enable ok to test for dependabot prs
- update golangci-lint to v1.53.x
- fix lints
/assign @saschagrunert @ameukam  @palnabarun 
cc @kubernetes/release-managers
> update golangci-lint to v1.53.x

- production.md
Update steps to scale down the replica set and then delete the PVC. This make sure that the old PVC does not get Bound to the new Pod, when only the pod is deleted. After the the old PVC is deleted and then recreated the replica can be scaled up.
Fixes: #364
> doc: update steps to cleanup PVC

- Makefile
- artifacts/manifests/podspec.yaml
Fixes #365 
This PR will change the memory limit from 1.6Gi to 1639Mi(_ceiling of `1638.4Mi`_) which does not represent a floating value.
1.6Gi = 1638.4 Mi = 1,677,721.6 Ki
1.5Gi = 1536 Mi = 1,572,864 Ki
> Fix fractional value memory limit

- Makefile
set CGO_ENABLED=0, so that static binaries are generated for the various publishing-bot components. This is needed because, when the build image `gcr.io/k8s-staging-releng/k8s-ci-builder:latest-default` was upgraded from bullseye to bookworm (kubernetes/release#3212), glibc version incompatibility occurred between the build machine and the prod cluster, preventing the bot from starting up.
> set CGO_ENABLED=0 for compiling publishing-bot

- Dockerfile
- Makefile
Let's try a fresh version of `git` to see if this gets past the problem with broken publishing-bot runs
> Bump debian and git version for publishing-bot

- artifacts/scripts/util.sh
This PR adds a line to initialize the subdirectories variable, which is currently causing issues because it is unbound, ref: https://github.com/kubernetes/kubernetes/issues/56876#issuecomment-1823178850
Fixes: #395
> initialize subdirectory variable

- .github/workflows/golangci-lint.yml
- .golangci.yml
- cmd/init-repo/main.go
- cmd/publishing-bot/config/rules.go
- cmd/publishing-bot/main.go
- cmd/publishing-bot/publisher.go
- cmd/publishing-bot/publisher_logger.go
- cmd/publishing-bot/publisher_logger_test.go
- cmd/publishing-bot/server.go
- cmd/sync-tags/gomod.go
- cmd/sync-tags/main.go
- cmd/update-rules/main.go
- cmd/validate-rules/staging/github_utils.go
- cmd/validate-rules/staging/validate.go
- hack/verify-golangci-lint.sh
- pkg/golang/install.go
Updating the linter to the latest release, enabling all gocritic linters and fixing them.
> Update golangci-lint to v1.55.2 and fix gocritic

- .gitignore
- cmd/update-rules/README.md
- cmd/update-rules/main.go
- cmd/update-rules/main_test.go
Adding support for removing branch
Fixes [#377](https://github.com/kubernetes/publishing-bot/issues/377) 
Cc: @akhilerm
> Adding support for removing branch

- cmd/validate-rules/main.go
- cmd/validate-rules/staging/validate.go
We now consider the `PULL_BASE_REF` (which is set by prow but for testing can also be empty) to:
- Check all rules when running on `master`
- Check only branch specific rules for release branches
Fixes https://github.com/kubernetes/publishing-bot/issues/433
cc @kubernetes/release-engineering
> Use `PULL_BASE_REF` for branch rules validation

- cmd/publishing-bot/publisher.go
The two usage of `publishedFileName` are not consistent.  Move this logic to inside the function.
> fix: make publishedFileName consistent

- go.mod
- update go minimal version to go1.23.0 as 1.22 is out of support and dependencies now need 1.23 as the minimal version
> update go minimal version to go1.23.0

- Dockerfile
A new debian version of git is available in the debian packages, which was updated as part of a security fix.
CHANGELOG: https://metadata.ftp-master.debian.org/changelogs//main/g/git/git_2.39.5-0+deb12u2_changelog
> update git version to 2.39.5-0+deb12u2

- .github/workflows/golangci-lint.yml
- update golangci-lint to v2.1.6
- update golangci-lint-action to v8.0.0
> build(dep): update golangci-lint to v2.1.6

- Makefile
I noticed that not all Make targets are `PHONY` which makes them impossible to run. We're facing that in the CI as well where `pull-publishing-bot-test` is never being ran, i.e. it always shows this instead of running tests:
```
make: 'test' is up to date.
```
(e.g. https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/publishing-bot/504/pull-publishing-bot-test/1963877011260706816)
This PR makes all Makefile targets `PHONY` which should fix such issues.
/assign @dims @sttts 
cc @kubernetes/release-engineering
> Change all Make targets to PHONY
